// Generated by dia2code
#ifndef STATE__ACTION__H
#define STATE__ACTION__H


namespace state {

  /// class Action - 
  class Action {
    // Operations
  public:
    void move ();
    void addFood ();
    void addCanon ();
    void addGold ();
    // Setters and Getters
  };

};

#endif
