// Generated by dia2code
#ifndef STATE__BOATHOLD__H
#define STATE__BOATHOLD__H

#include <memory>

namespace state {
  class Resources;
}

#include "Resources.h"

namespace state {

  /// class BoatHold - 
  class BoatHold {
    // Associations
    // Attributes
  private:
    std::unique_ptr<Resources>  resource;
    int quantity;
    // Operations
  public:
    void addResource (std::unique_ptr<Resource> newResource, int amount);
    // Setters and Getters
  };

};

#endif
