// Generated by dia2code
#ifndef STATE__CANON__H
#define STATE__CANON__H


namespace state {
  class Resources;
}

#include "Resources.h"

namespace state {

  /// class Canon - 
  class Canon : public state::Resources {
    // Operations
  public:
    string getType ();
    // Setters and Getters
  };

};

#endif
