// Generated by dia2code
#ifndef STATE__CARDS__H
#define STATE__CARDS__H


namespace state {
  class Action;
}

#include "Action.h"

namespace state {

  /// class Cards - 
  class Cards {
    // Associations
    // Attributes
  private:
    bool inUse;
    Action dayAction;
    Action nightAction;
    // Setters and Getters
  };

};

#endif
