// Generated by dia2code
#ifndef STATE__ENDING__H
#define STATE__ENDING__H


namespace state {
  class State;
}

#include "State.h"

namespace state {

  /// class Ending - 
  class Ending : public state::State {
    // Operations
  public:
    void rankPlayers ();
    // Setters and Getters
  };

};

#endif
