// Generated by dia2code
#ifndef STATE__FOOD__H
#define STATE__FOOD__H


namespace state {
  class Resources;
}

#include "Resources.h"

namespace state {

  /// class Food - 
  class Food : public state::Resources {
    // Operations
  public:
    string getType ();
    // Setters and Getters
  };

};

#endif
