// Generated by dia2code
#ifndef STATE__GAMECONFIG__H
#define STATE__GAMECONFIG__H


namespace state {
  class State;
}

#include "State.h"

namespace state {

  /// class GameConfig - 
  class GameConfig : public state::State {
    // Operations
  public:
    void setPlayerNumber ();
    void setPlayerName ();
    // Setters and Getters
  };

};

#endif
