// Generated by dia2code
#ifndef STATE__GAME__H
#define STATE__GAME__H

#include <vector>

namespace state {
  class State;
  class Player;
  class Map;
}

#include "State.h"
#include "Map.h"
#include "Player.h"

namespace state {

  /// class Game - 
  class Game {
    // Associations
    // Attributes
  public:
    State state;
    static int dayDice;
    static int nightDice;
  protected:
    int turn;
    std::vector<Player*> playerList;
    int captainIndex;
    // Operations
  public:
    void gameTurn (int time);
    // Setters and Getters
    int getTurn() const;
    void setTurn(int turn);
    const std::vector<Player*>& getPlayerList() const;
    void setPlayerList(const std::vector<Player*>& playerList);
    int getCaptainIndex() const;
    void setCaptainIndex(int captainIndex);
  };

};

#endif
