// Generated by dia2code
#ifndef STATE__GOLD__H
#define STATE__GOLD__H


namespace state {
  class Resources;
}

#include "Resources.h"

namespace state {

  /// class Gold - 
  class Gold : public state::Resources {
    // Operations
  public:
    string getType ();
    // Setters and Getters
  };

};

#endif
