// Generated by dia2code
#ifndef STATE__MAP__H
#define STATE__MAP__H

#include <vector>

namespace state {
  class Tile;
}

#include "Tile.h"

namespace state {

  /// class Map - 
  class Map {
    // Associations
    // Attributes
  public:
    std::vector<Tile> listOfTiles;
  protected:
    int size;
    // Setters and Getters
    int getSize() const;
    void setSize(int size);
  };

};

#endif
