// Generated by dia2code
#ifndef STATE__PLAYER__H
#define STATE__PLAYER__H

#include <vector>
#include <memory>

namespace state {
  class Treasure;
  class BoatHold;
  class Cards;
  class Player;
  class Resources;
}

#include "Treasure.h"
#include "BoatHold.h"
#include "Cards.h"
#include "Resources.h"

namespace state {

  /// class Player - 
  class Player {
    // Associations
    // Attributes
  private:
    std::vector <Treasure> treasures;
    std::vector <BoatHold> boatHolds;
    std::vector <Cards> cards;
  protected:
    int playerId;
    int Position;
    // Operations
  public:
    Player * choiceOpponent ();
    void fightOpponent ( Player *);
    void playTurn ();
    void setPosition (int movement = diceValue);
    int getPosition ();
    void addResourcesToBoatHold (int holdIndex, std::unique_ptr<Resources> resource, int amount = diceValue);
    void chooseTimeDice ();
    void chooseCard ();
    // Setters and Getters
    int getPlayerId() const;
    void setPlayerId(int playerId);
  };

};

#endif
