// Generated by dia2code
#ifndef STATE__PLAYING__H
#define STATE__PLAYING__H


namespace state {
  class State;
}

#include "State.h"

namespace state {

  /// class Playing - 
  class Playing : public state::State {
    // Operations
  public:
    void initMap ();
    void initPlayers ();
    // Setters and Getters
  };

};

#endif
