// Generated by dia2code
#ifndef STATE__RESOURCES__H
#define STATE__RESOURCES__H


namespace state {

  /// class Resources - 
  class Resources {
    // Operations
  public:
    virtual string getType ();
    // Setters and Getters
  };

};

#endif
