// Generated by dia2code
#ifndef STATE__TILE__H
#define STATE__TILE__H


namespace state {

  /// class Tile - 
  class Tile {
    // Attributes
  public:
    int foodCost;
    int goldCost;
    bool treasure;
    int nbPlayer;
    // Setters and Getters
  };

};

#endif
