// Generated by dia2code
#ifndef STATE__TREASURE__H
#define STATE__TREASURE__H


namespace state {

  /// class Treasure - 
  class Treasure {
    // Attributes
  public:
    int bonusGold;
    int malusGold;
    // Setters and Getters
  };

};

#endif
